apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-web-app
spec:
    replicas: 3
    selector:
      matchLabels:
        app: spring-boot-web-app
    template:
      metadata:
        labels:
          app: spring-boot-web-app
      spec:
        containers:
          - name: java-devops-app
            image: abkaplesh02/java-devops-app:v3
            ports:
              - containerPort: 8080
            envFrom:
              - configMapRef:
                  name: spring-boot-web-app-config


