apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-boot-web-app
spec:
    replicas: 3
    selector:
      matchLabels:
        app: spring-boot-web-app
    template:
      metadata:
        labels:
          app: spring-boot-web-app
      spec:
        containers:
          - name: spring-boot-web-app
            image: abkaplesh02/spring-boot-web-app:latest
            ports:
              - containerPort: 8080
            envFrom:
              - configMapRef:
                  name: spring-boot-web-app-config


