apiVersion: v1
kind: Service
metadata:
  name: spring-boot-web-app-service
spec:
  type: NodePort
  selector:
    app: spring-boot-web-app
    ports:
      - protocol: TCP
        port: 8080
        targetPort: 8080